# The URL the site will be built for
base_url = "/"
theme = "zola-private-dev-blog"
taxonomies = [ { name = "tags", feed = true } ]
generate_feed = true
build_search_index = false

highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true

[extra]
nav = [
  { name = "Home", path = "/" },
  { name = "Git Forge", path = "https://git.nickzana.dev" },
  { name = "Feed", path = "/atom.xml" },
  { name = "About", path = "/about/" },
]

accent = "#6b06a5"
accent_light = "#c98afc"

author = "Nick Zana"

not_found_message = """
This is not the page you're looking for... return back to [safety?](/)
"""
